//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taske
    {
        public int TaskId { get; set; }
        public string TaskTitle { get; set; }
        public string TaskDescription { get; set; }
        public string TaskStatus { get; set; }
        public string DueDate { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual User User { get; set; }
    }
}
